version: 2

models:
  - name: stg_customers
    description: '顧客テーブル'
    columns:
      - name: customer_id
        description: '顧客ID'
      - name: first_name
        description: '名'
      - name: last_name
        description: '姓'
      - name: loaded_at_jst
        description: 'ロード日時'
    data_tests:
      - dbt_utils.recency:
          datepart: day
          field: timestamp(loaded_at_jst, 'Asia/Tokyo')
          interval: '{{ 1 if target.name == prd else 7}}'

  - name: stg_orders
    description: '注文テーブル'
    columns:
      - name: order_id
        description: '注文ID'
      - name: customer_id
        description: '顧客ID'
        meta:
          metrics:
            num_unique_user_ids:
              type: count_distinct
            num_user_ids:
              type: count
      - name: order_date
        description: '注文日'
      - name: status
        description: '注文ステータス'
      - name: loaded_at_jst
        description: 'ロード日時'

  - name: stg_payments
    description: '支払いテーブル'
    columns:
      - name: id
        description: '支払いID'
      - name: order_id
        description: '注文ID'
      - name: payment_method
        description: '支払い方法'
      - name: amount
        description: '支払い金額'
      - name: loaded_at_jst
        description: 'ロード日時'
