version: 2

models:
  - name: stg_customers
    description: '{{ doc("table__raw_customers") }}'
    columns:
      - name: customer_id
        description: '{{ doc("column__raw_customers__id") }}'
      - name: first_name
        description: '{{ doc("column__raw_customers__first_name") }}'
      - name: last_name
        description: '{{ doc("column__raw_customers__last_name") }}'
      - name: loaded_at_jst
        description: 'ロード日時'
    data_tests:
      - dbt_utils.recency:
          datepart: day
          field: timestamp(loaded_at_jst, 'Asia/Tokyo')
          interval: '{{ 1 if target.name == prd else 7}}'

  - name: stg_orders
    description: ''
    columns:
      - name: order_id
        description: ''
      - name: customer_id
        description: ''
      - name: order_date
        description: ''
      - name: status
        description: ''

  - name: stg_payments
    description: ''
    columns:
      - name: id
        description: ''
      - name: order_id
        description: ''
      - name: payment_method
        description: ''
      - name: amount
        description: ''