dbt_project:
  outputs:
    dev:
      dataset: data_lake
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /Users/kohta/.key/gcp/dev-service-account-dbt.json
      location: US
      method: service-account
      priority: interactive
      project: dev-project-kohta-401305
      threads: 1
      type: bigquery
    prd:
      dataset: data_lake
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /Users/kohta/.key/gcp/prd-service-account-dbt.json
      location: US
      method: service-account
      priority: interactive
      project: prd-project-kohta-401305
      threads: 1
      type: bigquery
  target: dev

elementary:
  outputs:
    default:
      type: "bigquery"
      project: "dev-project-kohta-401305"
      dataset: "data_lake_elementary"
      method: service-account
      keyfile: /Users/kohta/.key/gcp/dev-service-account-dbt.json
      priority: interactive
      threads: 1