version: 2

models:
  - name: stg_customers
    description: ''
    columns:
      - name: id
        description: ''
      - name: first_name
        description: ''
      - name: last_name
        description: ''

  - name: stg_orders
    description: ''
    columns:
      - name: order_id
        description: ''
      - name: customer_id
        description: ''
      - name: order_date
        description: ''
      - name: status
        description: ''

  - name: stg_payments
    description: ''
    columns:
      - name: id
        description: ''
      - name: order_id
        description: ''
      - name: payment_method
        description: ''
      - name: amount
        description: ''